# Generated by Django 3.2 on 2024-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Anonymous'), (1, 'User'), (2, 'Moderator'), (3, 'Admin'), (4, 'Superuser')], default=1, max_length=150),
        ),
    ]
